### PR TITLE
fixed makefile

### LINKED ISSUE #36: CI and makefile are inconsistent
Seems something has changed between versions in ghostscript? The flag `-ta4` does not work in newer versions, and its not consistent in the makefile and CI

* https://github.com/f-klubben/sangbog/blob/main/.github/workflows/compile.yml#L30
* https://github.com/f-klubben/sangbog/blob/main/Makefile#L17

Also removing the flag does not seemingly change anything in the output pdf?

### PR DESCRIPTION
**Pull request by Mast3rwaf1z**
fixes #36 

i have not checked the pdf beyond the first 10 pages, but the flag does not seem to change the output of the makefile

### CODE REVIEW

**Comment by mads256h** [comment]
It is supposed to make the papersize A4. Check if the output is different

**Comment by Mast3rwaf1z** [comment]
`man dvips` says that `dvips -t a4` does the same, i'd say that's good enough?

**Comment by mads256h** [comment]
Yeah dvipdf is a wrapper around dvips. I think dvipdf complains and then passes the options on to dvips.
Is that screenshot with or without -ta4?

**Comment by Mast3rwaf1z** [comment]
> Is that screenshot with or without -ta4?

without

**Comment by mads256h** [comment]
I does fuck all then lol

**Review by mads256h — APPROVED** [review]

**Comment by Mast3rwaf1z** [comment]
`-sPAPERSIZE=a4` seems to do the same as far as i can read, i think its a parameter passed to `gs`, but i'm not sure

**Comment by Mast3rwaf1z** [comment]
waiting on #35

**Comment by mads256h** [comment]
> `-sPAPERSIZE=a4` seems to do the same as far as i can read, i think its a parameter passed to `gs`, but i'm not sure

We should probably upgrade to pdflatex sometime in the future.
This stuff is pretty old, slow, and finicky.

**Comment by JakobTopholt** [comment]
@Mast3rwaf1z Am I correct in understanding that you wanted to test it after #35 was merged?

**Comment by Mast3rwaf1z** [comment]
> @Mast3rwaf1z Am I correct in understanding that you wanted to test it after #35 was merged?

It's mostly so I make sure this pr doesn't break CI

**Pull request merged**
