### PR TITLE
Update paacassiopeiatilfoobar.tex

### PR DESCRIPTION
**Pull request by JakobTopholt**
Added collumns, this should make the osng one page

### CODE REVIEW

**Comment by JakobTopholt** [comment]
I'll check if it actually is one page later, or someone else can.

**Comment by krestenlaust** [comment]
The Latex doesn't comple

**Comment by JakobTopholt** [comment]
Let's check if going back to one column makes it compile

**Comment by JakobTopholt** [comment]
I simply forgor to end the /spal with /laps.

It passes now.

**Comment by krestenlaust** [comment]
Status brother

**Comment by JakobTopholt** [comment]
Vi cooker

**Pull request merged**
