### PR TITLE
0-indexing the sangbog, as it should be

### PR DESCRIPTION
**Pull request by Mast3rwaf1z**
i think it might be a good idea to add a new song at index 0 so the song indices are consistent with previous versions, though it would also mess with which page each song is on. For example, song 7 will now be song 6, but it will still be on page 17, but if another song is added at index 0, song 7 will be moved to page 18 or 19.

some comments changed even with editing on github, might be an encoding issue?

### CODE REVIEW

**Comment by Mast3rwaf1z** [comment]
[main.pdf](https://github.com/f-klubben/sangbog/files/12929961/main.pdf)

**Review by JakobTopholt — APPROVED** [review]
Thomas påstår at det virker det må være en LGTM.

**Comment by krestenlaust** [comment]
Han har admin nu

**Comment by krestenlaust** [comment]
The book was already 0-indexed, now it's -1-indexed, a little silly making the whole book go out of order to do this

**Comment by Mast3rwaf1z** [comment]
> The book was already 0-indexed, now it's -1-indexed, a little silly making the whole book go out of order to do this

The sangbog should be incrementing the index before inserting the number, making the compiled book appear 0-indexed in the compiled version

i agree that its janky tho, i've compiled the master branch and attached how the book looks compiled
[main_book.pdf](https://github.com/f-klubben/sangbog/files/14993961/main_book.pdf)

**Pull request merged**
